# -*- coding: utf-8 -*-
"""exercicios/codigos aulas tuplas, listas e dicionários

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tfIndRJZQPcv9TxXUHc0uPJVHAqgaAR4
"""

#para alterar uma tupla, é necessário transforma-la em lista
tupla = (10,20,30,40)
tupla = list(tupla)
tupla.append(50)
tupla
tupla = tuple(tupla)
tupla

var1,var2,var3,var4,var5 = tupla
var1



frutas = {"banana": 3.0,
 "cebola": 4.0,
 "maçã": 5.7,
 "abacaxi": 8.0}

frutas["maçã"] = 8.6
print(f"O dicionário de frutas é: {frutas}")

#fazendo alterações em meu dicionário
pessoa = {"nome": "José",
 "idade": 32,
 "profissao": "empreendedor",
 "filhos": ["Ana", "Bernardo", "Joao"]}

pessoa["nacionalidade"] = "Brasileiro"
pessoa["filhos"][2]

#alteração no meu dicionário com função
pessoa.update({"idade": 35,"nacionalidade": "chilento","cachorro": "zeus"})

#passamos uma chave e ele apaga chave e valor
pessoa.pop("nome")

## remove última chave valor do dicionário
pessoa.popitem()

##alterar o nome da chave
pessoa["netos"] = pessoa.pop("filhos")

#iterações com dicionários

for chave in pessoa.keys():
  print(chave)

#acessando pela função values
for valores in pessoa.values():
  print(valores)

#acessando valores pela chave
for elementos in pessoa['netos']:
  print(elementos)

for seq,chave in enumerate(pessoa):
  print(seq,chave)

for chave,valor in pessoa.items():
  print(f"A chave {chave} possui valor {valor}.")

cadastro = {
    "nome": "joao",
    "endereco": {
        "rua": "rua travessa",
        "cep" : 200439424
    }
}

cadastro[]

"""3) Faça uma função que conte quantas vezes cada elemento aparece em uma lista. Essa função deverá guardar os dados em um dicionário no qual as chaves são os elementos inseridos e os valores são a contagem de quantas vezes esse elemento aparece. ex de output: {"banana":2, "maçã":1}"""

def criacaodicionario (elementos):

  dicionario = {}

  for elemento in elementos:
    dicionario[elemento] = elementos.count(elemento)

  return dicionario

"""4) Faça uma função que receba múltiplos números inteiros em seguida informe quantos são pares e quantos são ímpares."""

def par_impar(elementos):

  par = 0
  impar = 0

  for elemento in elementos:
    if elemento % 2 == 0:
      par += 1
    else:
      impar += 1

  return (f"{par} pares e {impar} impares")

teste = (1,2,3,4,5,5,74,467,5,4) 

par_impar(teste)

"""5) faça uma função que recebe um elemento a ser encontrado no texto e substitui por outro elemento"""

def trocar (string,dicionario): #suco de abacaxi - "a":A , "s": S
  nova_string = string[:]
  for chave,valor in dicionario.items():
   nova_string = nova_string.replace(chave,valor)
  return nova_string

trocar("suco de abacaxi",{"a":"A","s":"S"})

"""6) Faça um código contador de palavras. O usuário vai inserir um texto qualquer e o programa vai contar a quantidade de cada palavra no texto, armazenando o resultado em um dicionário e exibindo o resultado para o usuário.

caso queira pode utilizar o .split() e .replace()
"""

def contarpalavra (texto):

  dic = {}
  for palavras in texto.split():
    dic[palavras] = texto.count(palavras)

  return dic

contarpalavra("O brasil brasil vai ganhar a copa !!!")
